from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi


qreg_q = QuantumRegister(5, 'q')
creg_c = ClassicalRegister(5, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)



circuit.cx(qreg_q[3], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi, qreg_q[0])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(pi / 2, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi, qreg_q[0])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(pi / 2, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(pi / 2, qreg_q[0])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(pi / 2, qreg_q[0])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[2])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[0])
circuit.rz(-pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.rz(-pi, qreg_q[2])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(-pi, qreg_q[4])
circuit.measure(qreg_q[1], creg_c[4])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[2])
circuit.cx(qreg_q[2], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(pi / 2, qreg_q[1])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(pi / 2, qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.measure(qreg_q[1], creg_c[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.cx(qreg_q[1], qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(-pi, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi / 2, qreg_q[3])
circuit.rz(-pi, qreg_q[4])
circuit.cx(qreg_q[4], qreg_q[3])
circuit.rz(-pi / 2, qreg_q[3])
circuit.cx(qreg_q[3], qreg_q[1])
circuit.rz(-pi, qreg_q[1])
circuit.rz(pi / 2, qreg_q[3])
circuit.rz(pi / 2, qreg_q[4])
circuit.cx(qreg_q[3], qreg_q[4])
circuit.cx(qreg_q[1], qreg_q[3])
circuit.measure(qreg_q[1], creg_c[0])
circuit.measure(qreg_q[3], creg_c[2])
circuit.measure(qreg_q[4], creg_c[3])

cost = circuit.count_ops()['cx']
print(cost)
print(circuit.depth()-5)